## Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

export EDITOR='micro'
export LANG=en_US.UTF-8
# SSH Agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

##
## Oh my ZSH Plugins
###
plugins=(
  command-not-found
  git
  sudo
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# autoload -Uz compinit
# compinit

# source $ZSH/oh-my-zsh.sh
# setopt inc_append_history
# setopt share_history

##
## Prompt
##
# export STARSHIP_CONFIG=~/.config/starship/config.toml
# eval "$(init zsh)"

