repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-validate
      - id: terraform-fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: checkov

# pre-commit autoupdate
# pre-commit run -a
