#  https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
additionalArguments:
  - --providers.file.filename=/data/traefik-config.yaml
  #  - - --ping
  #  - --ping.entrypoint=web
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
  - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
#  - --certificatesresolvers.dns-cloudflare.acme.dnschallenge=true
  - --certificatesresolvers.cloudflare.acme.email=${EMAIL}
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
  - --log.level=INFO
  - --metrics.prometheus
  #  - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
  - --accesslog=true
  - --accesslog.format=json
  - --accesslog.filepath=/data/access.log
#  - "--tracing.jaeger=true"
#  - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.default.svc:5778/sampling"
#  - "--tracing.jaeger.localAgentHostPort=jaeger-agent.default.svc:6831"

ports:
  web:
    redirectTo: websecure

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  path: /certs
  size: 128Mi
#  existingClaim: "ingress-traefik-volume-claim"

volumes:
  - mountPath: /data
    name: traefik-config
    type: configMap

logs:
  general:
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    enabled: true

# enabling this doesn't create default middlewares!
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 3
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50
#    - type: Resource
#      resource:
#        name: memory
#        targetAverageUtilization: 50
