apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: "default"
  namespace: "${namespace}"
spec:
 addresses: ["${default_address_pool}"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: "default"
  namespace: "${namespace}"
spec:
 ipAddressPools: ["default"]
