- hosts: node
  tasks:
#    - name: Add ssh keys
#      ansible.posix.authorized_key:
#        user: banana
#        state: present
#        key: "{{ lookup('file', '~/.ssh/pi/id_rsa.pub') }}"

    - name: Check system information
      shell:
        "lsb_release -a"
      register: os_info
    - debug:
        msg: "{{os_info.stdout_lines}}"
    
    - name: Configure dpkg
      become: yes
      shell:
        "dpkg --configure -a"
    
    - name: Copy undervoltage script
    #   ansible.builtin.script: ./scripts/undervoltage.sh
    #   args:
    #     executable: bash
    #   register: undervoltage
    # - debug: msg="{{ undervoltage.stdout.split('\n') }}"
      copy:
        src: ./scripts/undervoltage.sh
        dest: ~/undervoltage.sh
        mode: a+x

    - name: Copy temperature script
    #   ansible.builtin.script: ./scripts/temperature.sh
    #   args:
    #     executable: bash
    #   register: temperature
    # - debug: msg="{{ temperature.stdout.split('\n') }}"
      copy:
        src: ./scripts/temperature.sh
        dest: ~/temperature.sh
        mode: a+x

    - name: Update all packages to their latest version
      become: yes
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      become: yes
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Pass options to dpkg on run
      become: yes
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        dpkg_options: 'force-confold,force-confdef'

    - name: Install packages
      become: yes
      apt:
        name:
          - tree
          - micro
          - zsh
          - git
          - ufw
          - net-tools
          - htop
          - autoconf
          - ffmpeg
          - v4l-utils # camera
          - open-iscsi # longhorn-driver-deployer
          - linux-modules-extra-raspi # https://docs.k3s.io/installation/requirements?os=pi#ubuntu-vxlan-module
        state: latest
        cache_valid_time: 600

    # RUN!!! ansible-galaxy install gantsign.oh-my-zsh
    - name: run role for each user
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "banana"
            update_mode: auto
            update_frequency: 10
            oh_my_zsh:
              theme: robbyrussell # robbyrussell # spaceship
              plugins:
                - git
                - zsh-syntax-highlighting
                - zsh-autosuggestions
                - zsh-completions
#                - docker

    - name: Install spaceship prompt
      git:
        repo: https://github.com/spaceship-prompt/spaceship-prompt.git
        dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
        depth: 1

    - name: Enable spaceship theme
      file:
        src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
        dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
        state: link

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1
    - name: Install zsh-completions
      git:
        repo: https://github.com/zsh-users/zsh-completions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1

    - name: Change shell to zsh
      become: yes
      user:
        name: "banana"
        shell: /bin/zsh

    - name: Remove useless packages from the cache
      become: yes
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: yes
      ansible.builtin.apt:
        autoremove: yes

    - name: Run the equivalent of "apt-get clean" as a separate step
      become: yes
      apt:
        clean: yes

    # Allow OpenSSH. (Note that as ufw manages its own state, simply removing
    # a rule=allow task can leave those ports exposed. Either use delete=true
    # or a separate state=reset task)
    - name: allow 22
      become: yes
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Set logging
      become: yes
      community.general.ufw:
        logging: 'on'

    # Sometimes it is desirable to let the sender know when traffic is
    # being denied, rather than simply ignoring it. In these cases, use
    # reject instead of deny. In addition, log rejected connections:
    - name: reject all
      become: yes
      community.general.ufw:
        rule: reject
        port: auth
        log: true
    
    - name: enable UFW
      become: yes
      community.general.ufw:
        state: enabled

    - name: Reboot
      become: yes
      ansible.builtin.reboot:
        reboot_timeout: 300

#    - name: Install Docker
#      ansible.builtin.command:
#        cmd:
#          - curl -fsSL https://get.docker.com -o get-docker.sh
#          - sudo sh get-docker.sh
#          - sudo usermod -aG docker "banana"