- hosts: all
  become: yes
  tasks:
    - name: Check system information
      shell:
        "lsb_release -a"
      register: os_info
    - debug:
        msg: "{{os_info.stdout_lines}}"

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - tree
          - micro
          - zsh
          - ufw
          - net-tools
        state: latest
        cache_valid_time: 3600

#  configure zsh here!!

# sudo update-alternatives --config iptables
    - name: Apply UFW rules
      ansible.builtin.import_tasks: ufw.yaml

    - name: Increase size of the buffer that receives UDP packets
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: '2500000'
        sysctl_set: yes
        reload: yes

    - name: Under voltage?
      ansible.builtin.script: ./scripts/undervoltage.sh
      args:
        executable: bash
      register: undervoltage
    - debug: msg="{{ undervoltage.stdout.split('\n') }}"

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes

    - name: Run the equivalent of "apt-get clean" as a separate step
      apt:
        clean: yes

- hosts: master
  become: yes
  tasks:
    - community.general.ufw:
        rule: allow
        port: 2379:2380
        proto: tcp

- hosts: node
  become: yes
  tasks:
    - community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 60

- hosts: all
  become: yes
  tasks:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        default: deny



